public class ContactWrapper {
    
    public String Id{get; set;}
    public String FirstName{get; set;}
    public String LastName{get; set;}
    public String Email{get; set;}
    public String Title{get; set;}
    public String Organization{get; set;}
    public String Street{get; set;}
    public String Country{get; set;}
    public String City{get; set;}
    public String State{get; set;}
    public String Zip{get; set;}
    public String Phone{get; set;}

}